steps:
  - name: node:17
    entrypoint: npm
    args: ["install"]

  - name: node
    entrypoint: npm
    args: ["run", "build"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["rsync", "-r", "dist/", "gs://${_BUCKET_NAME}"]

substitutions:
  _BUCKET_NAME: "bucket_build"

serviceAccount: "cloud-build-service-account@my-kubernetes-project-444304.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
