steps:
  
  - name: node:17.0.0
    entrypoint: npm
    args: ["install"]


  - name: node:17.0.0
    entrypoint: npm
    args: ["run", "build", "--", "--base-href=/bucket-build/espl-website/"]


  - name: gcr.io/cloud-builders/gsutil
    args: ["rsync", "-r", "dist/", "gs://${_BUCKET_NAME}"]

substitutions:
  _BUCKET_NAME: "bucket_build" 

serviceAccount: "cloud-build-service-account@my-kubernetes-project-444304.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
