steps:
  - name: node
    entrypoint: npm
    args: ["install"]

  - name: node
    entrypoint: npm
    args: ["run", "build"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["rsync", "-r", "dist/", "gs://${_BUCKET_NAME}"]

substitutions:g
  _BUCKET_NAME: "bucket_build" 

  serviceAccount: "cloud-build-service-account@your-project-id.iam.gserviceaccount.com"

  options:
  logging: CLOUD_LOGGING_ONLY